version: '3.1'

services:

  redmine:
    image: redmine
    container_name: redmine
    restart: always
    ports:
      - 80:3000
    volumes:
      - ${HOME}/docker/volumes/redmine/plugins:/usr/src/redmine/plugins
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD=123456
    links:
      - db

  db:
    image: mysql:5.7
    container_name: redmine_db
    restart: always
    ports:
      - 13306:3306
    volumes:
      - ${HOME}/docker/volumes/redmine_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=redmine
